// <auto-generated />
namespace Exercise3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Validator : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Validator));
        
        string IMigrationMetadata.Id
        {
            get { return "202107061640555_Validator"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
